### Logistic Regression Implementation

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [10]:
##create dataset
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [12]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [11]:
X.shape

(1000, 10)

In [13]:
X=pd.DataFrame(X)

In [14]:
X.head()

0         1         2         3         4         5         6  \
0  0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1 -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2 -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3  1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4 -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   

          7         8         9  
0 -1.210161 -0.628077  1.227274  
1 -0.984534  0.363896  0.209470  
2 -0.246383 -1.058145 -0.297376  
3 -0.357445 -1.473127 -0.190039  
4 -0.939156  0.175915  0.236224

In [16]:
y.shape

(1000,)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=2)

In [19]:
#Model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [20]:
logistic.fit(X_train,y_train)


LogisticRegression()

In [21]:
logistic.intercept_

array([0.16550957])

In [22]:
logistic.coef_

array([[-0.48335969,  0.1810028 , -0.76429221,  0.12327359, -0.04683165,
        -0.1614612 ,  1.6338469 ,  0.05216944, -0.56726861,  0.01611338]])

In [24]:
y_pred = logistic.predict(X_test)

In [25]:
logistic.predict_proba(X_test)

array([[7.52888243e-01, 2.47111757e-01],
       [6.63570093e-01, 3.36429907e-01],
       [5.84258375e-01, 4.15741625e-01],
       [8.11381229e-01, 1.88618771e-01],
       [8.69272710e-03, 9.91307273e-01],
       [8.93539255e-02, 9.10646075e-01],
       [4.91808554e-01, 5.08191446e-01],
       [7.95393324e-01, 2.04606676e-01],
       [4.35986327e-02, 9.56401367e-01],
       [6.09262999e-02, 9.39073700e-01],
       [7.71763390e-01, 2.28236610e-01],
       [9.81272563e-01, 1.87274373e-02],
       [1.13275374e-01, 8.86724626e-01],
       [6.38142409e-04, 9.99361858e-01],
       [3.39320408e-01, 6.60679592e-01],
       [9.37291752e-01, 6.27082485e-02],
       [2.10724522e-02, 9.78927548e-01],
       [1.12550524e-01, 8.87449476e-01],
       [1.47261240e-01, 8.52738760e-01],
       [9.79272459e-01, 2.07275408e-02],
       [9.81532338e-02, 9.01846766e-01],
       [8.72484984e-01, 1.27515016e-01],
       [9.98168228e-01, 1.83177221e-03],
       [2.68623209e-03, 9.97313768e-01],
       [5.246300

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [28]:
score=accuracy_score(y_test,y_pred)
print(score)

0.8633333333333333


In [30]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[120  16]
 [ 25 139]]


In [31]:
print(f'classifiacation matrix: {classification_report(y_pred,y_test)}')

classifiacation matrix:               precision    recall  f1-score   support

           0       0.88      0.83      0.85       145
           1       0.85      0.90      0.87       155

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300

